# Generated by Django 5.2.8 on 2025-11-18 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="apps.app",
                    ),
                ),
            ],
        ),
    ]
