# Generated by Django 5.2.8 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='category',
        ),
        migrations.AddField(
            model_name='app',
            name='categories',
            field=models.ManyToManyField(null=True, related_name='apps', to='category.category'),
        ),
    ]
