# Generated by Django 5.2.8 on 2025-12-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='apps.app')),
            ],
        ),
    ]
