# Generated by Django 5.2.8 on 2025-11-18 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='apps.app')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='organizations.organization')),
            ],
            options={
                'unique_together': {('app', 'organization')},
            },
        ),
    ]
