# Generated by Django 5.2.8 on 2025-12-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('installation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='config',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='config.config'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='installed_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
    ]
