# Generated by Django 5.2.8 on 2025-11-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("school_admin", "School Admin"),
                            ("teacher", "Teacher"),
                            ("parent", "Parent"),
                            ("student", "Student"),
                            ("developer", "Developer"),
                            ("marketplace_admin", "Marketplace Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="user_icons/"),
                ),
                (
                    "active",
                    models.CharField(
                        choices=[("active", "Active"), ("disable", "Disable")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "organizations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
